spring.application.name=Servicio_de_Autenticacion_y_Autorizacion

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=1234

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/auth}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración para manejar reintentos de conexión
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=30000

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Codificacion
spring.mandatory-file-encoding=UTF-8

# Actuator
management.endpoints.web.exposure.include=*

# Configuración JWT
app.jwtSecret=QWERTYUIOPASDFGHJKLZXCVBNMQWERTYUIOPASDFGHJKLZXCVBNMQWERTYUIOPASDFGHJKLZXCVBNM
#1 día en milisegundos
app.jwtExpirationMs=86400000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html


spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:5500
# Configuración de CORS
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS 
# Permitir todos los encabezados
spring.web.cors.allowed-headers=*
# Permitir credenciales (cookies, autenticación HTTP básica, etc.)
spring.web.cors.allow-credentials=true

#Swagger
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false



